### ISSUE TITLE
Typing mistake- Remove unnecessary Single low quote

### ISSUE THREAD

**Issue by merinpriyasha** [AshenIR/Resume_Website#6]
![Capture6](https://user-images.githubusercontent.com/68733175/149293243-fe8ed7e2-d22a-4be4-bac1-437e83112889.PNG)

* The word "SKILL'S" in the above section should be changed to "SKILLS".
* Remove Single low quote ( ' )between L and S

**Comment by AshenIR** [comment]
correct the issue
